export class ElementTag {
    #value;

    constructor(value) {
        this.#value = value;
        Object.freeze(this);
    }

    toString() { return this.#value; }

    static A          = new ElementTag('a');
    static ABBR       = new ElementTag('abbr');
    static ADDRESS    = new ElementTag('address');
    static AREA       = new ElementTag('area');
    static ARTICLE    = new ElementTag('article');
    static ASIDE      = new ElementTag('aside');
    static AUDIO      = new ElementTag('audio');
    static B          = new ElementTag('b');
    static BASE       = new ElementTag('base');
    static BDI        = new ElementTag('bdi');
    static BDO        = new ElementTag('bdo');
    static BLOCKQUOTE = new ElementTag('blockquote');
    static BODY       = new ElementTag('body');
    static BR         = new ElementTag('br');
    static BUTTON     = new ElementTag('button');
    static CANVAS     = new ElementTag('canvas');
    static CAPTION    = new ElementTag('caption');
    static CITE       = new ElementTag('cite');
    static CODE       = new ElementTag('code');
    static COL        = new ElementTag('col');
    static COLGROUP   = new ElementTag('colgroup');
    static DATA       = new ElementTag('data');
    static DATALIST   = new ElementTag('datalist');
    static DD         = new ElementTag('dd');
    static DEL        = new ElementTag('del');
    static DETAILS    = new ElementTag('details');
    static DFN        = new ElementTag('dfn');
    static DIALOG     = new ElementTag('dialog');
    static DIV        = new ElementTag('div');
    static DL         = new ElementTag('dl');
    static DT         = new ElementTag('dt');
    static EM         = new ElementTag('em');
    static EMBED      = new ElementTag('embed');
    static FIELDSET   = new ElementTag('fieldset');
    static FIGCAPTION = new ElementTag('figcaption');
    static FIGURE     = new ElementTag('figure');
    static FOOTER     = new ElementTag('footer');
    static FORM       = new ElementTag('form');
    static H1         = new ElementTag('h1');
    static H2         = new ElementTag('h2');
    static H3         = new ElementTag('h3');
    static H4         = new ElementTag('h4');
    static H5         = new ElementTag('h5');
    static H6         = new ElementTag('h6');
    static HEAD       = new ElementTag('head');
    static HEADER     = new ElementTag('header');
    static HGROUP     = new ElementTag('hgroup');
    static HR         = new ElementTag('hr');
    static HTML       = new ElementTag('html');
    static I          = new ElementTag('i');
    static IFRAME     = new ElementTag('iframe');
    static IMG        = new ElementTag('img');
    static INPUT      = new ElementTag('input');
    static INS        = new ElementTag('ins');
    static KBD        = new ElementTag('kbd');
    static LABEL      = new ElementTag('label');
    static LEGEND     = new ElementTag('legend');
    static LI         = new ElementTag('li');
    static LINK       = new ElementTag('link');
    static MAIN       = new ElementTag('main');
    static MAP        = new ElementTag('map');
    static MARK       = new ElementTag('mark');
    static MENU       = new ElementTag('menu');
    static META       = new ElementTag('meta');
    static METER      = new ElementTag('meter');
    static NAV        = new ElementTag('nav');
    static NOSCRIPT   = new ElementTag('noscript');
    static OBJECT     = new ElementTag('object');
    static OL         = new ElementTag('ol');
    static OPTGROUP   = new ElementTag('optgroup');
    static OPTION     = new ElementTag('option');
    static OUTPUT     = new ElementTag('output');
    static P          = new ElementTag('p');
    static PICTURE    = new ElementTag('picture');
    static PRE        = new ElementTag('pre');
    static PROGRESS   = new ElementTag('progress');
    static Q          = new ElementTag('q');
    static RP         = new ElementTag('rp');
    static RT         = new ElementTag('rt');
    static RUBY       = new ElementTag('ruby');
    static S          = new ElementTag('s');
    static SAMP       = new ElementTag('samp');
    static SCRIPT     = new ElementTag('script');
    static SEARCH     = new ElementTag('search');
    static SECTION    = new ElementTag('section');
    static SELECT     = new ElementTag('select');
    static SLOT       = new ElementTag('slot');
    static SMALL      = new ElementTag('small');
    static SOURCE     = new ElementTag('source');
    static SPAN       = new ElementTag('span');
    static STRONG     = new ElementTag('strong');
    static STYLE      = new ElementTag('style');
    static SUB        = new ElementTag('sub');
    static SUMMARY    = new ElementTag('summary');
    static SUP        = new ElementTag('sup');
    static TABLE      = new ElementTag('table');
    static TBODY      = new ElementTag('tbody');
    static TD         = new ElementTag('td');
    static TEMPLATE   = new ElementTag('template');
    static TEXTAREA   = new ElementTag('textarea');
    static TFOOT      = new ElementTag('tfoot');
    static TH         = new ElementTag('th');
    static THEAD      = new ElementTag('thead');
    static TIME       = new ElementTag('time');
    static TITLE      = new ElementTag('title');
    static TR         = new ElementTag('tr');
    static TRACK      = new ElementTag('track');
    static U          = new ElementTag('u');
    static UL         = new ElementTag('ul');
    static VAR        = new ElementTag('var');
    static VIDEO      = new ElementTag('video');
    static WBR        = new ElementTag('wbr');
}

Object.freeze(ElementTag);
